rust-fuzz/libfuzzer

- README.md
Fixes https://github.com/rust-fuzz/libfuzzer-sys/issues/1.
> Indicate Linux only support for libfuzzer-sys.

- README.md
The example code doesn't work since it still uses the old crate name. This PR fixes it.
> Use new crate name in example

- .travis.yml
- Cargo.toml
- example_arbitrary/Cargo.toml
- example_arbitrary/src/main.rs
- src/lib.rs
Not efficient[1], but that mostly needs work on the arbitrary crate, as
opposed to work on libfuzzer-sys.
[1]: fuzzing struggles with e.g.
fuzz_target!(|data: String| { if data == "banana" { panic!() } });
and takes quite a while to find an input that fails the check (compared
to fuzzing against raw bytes). It seems to me that to take full
advantage of fuzzing structured data, one would have to adjust libFuzzer
somehow or, perhaps, rewrite libFuzzer in rust having precisely
structured fuzzing in mind.
> Support for arbitrary data types

- build.rs
Tweak build.rs so that it's possible to use a custom libFuzzer.a
archive. This is necessary when using OSS-Fuzz
(https://github.com/google/oss-fuzz): the build
system has to link with the libFuzzer provided by
the `LIB_FUZZING_ENGINE` environment variable (see
https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md)
> Optionally use a custom libFuzzer.a archive

- Cargo.toml
- build.rs
Also, the gcc's Config type is renamed to Build in cc.
Ref. https://users.rust-lang.org/t/the-gcc-crate-is-now-cc-1-0-0/12961
> Rename and update gcc crate to cc

- Cargo.toml
- README.md
- build.rs
- example/Cargo.toml
- example/src/main.rs
- example_arbitrary/Cargo.toml
- example_arbitrary/src/main.rs
- src/lib.rs
Also update to 2018 edition.
Fixes #42
> Fix `fuzz_target!` with `Arbitrary`-implementing types

- src/lib.rs
Currently `cargo fuzz` fails because it can't find `arbitrary` (caused by https://github.com/rust-fuzz/libfuzzer-sys/pull/43). We should either do this or tweak `cargo fuzz init` to add an explicit dependency on `arbitrary`
r? @fitzgen
> Reexport arbitrary crate

- src/lib.rs
Resolves #36.
The default hook prints the error message, and optionally the backtrace if RUST_BACKTRACE=1 is set, before aborting. This information is very useful to understand the panic and fix the code. While this information was already printed on mac OS before this PR, the information was not present on linux. The information printed now looks like: 
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: BufferTooShort', src/libcore/result.rs:1165:5
stack backtrace:
0: backtrace::backtrace::libunwind::trace
at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
1: backtrace::backtrace::trace_unsynchronized
at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs: …
```
> Run default panic hook before aborting

- build.rs
Apologies in advance for this hack job.
As part of https://github.com/bytecodealliance/wasmtime/issues/611 I am building wasmtime fuzz targets in the google/oss-fuzz build container. This environment supplies the LLVM c++ standard library rather than the GCC one. It is specified in `CXXFLAGS` and presumably linked in the version of libfuzzer they supplied (`libFuzzingEngine.a`).
It looks like rust-fuzz/libfuzzer currently [links the GCC standard library when using an external libfuzzer library](https://github.com/rust-fuzz/libfuzzer/blob/cc49a08fd7c20b669b4491f6c61054c570eedda0/build.rs#L12), which causes a linker error when linking in the oss-fuzz compilation environment.
This PR adds an environment variable that lets the user select whether they'd like to link the GCC c++ standard …
> Add env var to select c++ std lib

- ci/script.sh
Level 4 seems to have been removed in:
https://github.com/llvm/llvm-project/commit/c5d3d490340fd32698ef9f29b80e97a4c1e95d11#diff-32378db1cb0e8e11ecfc62eda7181acadc661910d4e3ab214babb65af95bc7e9
> Remove usage of sanitizer-coverage-level=4

- README.md
libfuzzer defaults to `trace-pc-guard`, but that seems to be removed
now:
- https://github.com/rust-fuzz/libfuzzer/issues/66
- ~https://github.com/llvm/llvm-project/commit/c5d3d490340fd32698ef9f29b80e97a4c1e95d11#diff-32378db1cb0e8e11ecfc62eda7181acadc661910d4e3ab214babb65af95bc7e9~ meant to link to https://github.com/llvm/llvm-project/commit/62d727061053dac28447a900fce064c54d366bd6
And confusingly, their docs still mention `trace-pc-guard`:
- https://github.com/llvm/llvm-project/blob/master/clang/docs/SanitizerCoverage.rst
> Tell users to use inline-8bit-counters.

- src/lib.rs
Adds a dummy documentation for `rust_fuzzer_test_input`.
When passing `-Fmissing_docs` to cargo CLI, `libfuzzer-sys` won't compile because of the non-documented public auto-generated function.
> Document `rust_fuzzer_test_input`

- Cargo.toml
- src/lib.rs
Currently if someone doesn't use `RUST_LIBFUZZER_DEBUG_PATH` they still need to pay an allocation (to convert to `CString`) a Mutex lock, and a `getenv(3)` call for every fuzzing input.
Instead we can check and load the environment variable at initialization and from then it will be almost free for users that don't set the environment variable.
(this is slightly a behavior change as before someone could attach a debugger and modify the enviroment variable while it's fuzzing but now they can't, but I don't think it matters)
> Make RUST_LIBFUZZER_DEBUG_PATH "free" for non-users

- src/lib.rs
For fuzz targets that use `libfuzzer_sys::fuzz_target!(|arg: &[u8]| {})` directly without `#[macro_use]`ing `libfuzzer_sys`, the compilation failed:
```
error: cannot find macro `fuzz_target` in this scope
--> [$HOME]/.cargo/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.4.2/src/lib.rs:161:9
|
137 | / macro_rules! fuzz_target {
138 | |     (|$bytes:ident| $body:block) => {
139 | |         /// Auto-generated function
140 | |         #[no_mangle]
...   |
161 | |         fuzz_target!(|$data| $body);
| |         ^^^^^^^^^^^
...   |
207 | |     };
208 | | }
| |_- in this expansion of `libfuzzer_sys::fuzz_target!`
|
::: fuzz_targets/bare.rs:3:1
|
3   | / libfuzzer_sys::fuzz_target!(|data: &[u8]| {
4   | |     // fuzzed code goes here
5   | | });
| |___- in this macro invocation
|
= …
```
> Use absolute path to fuzz_target! macro in macro recursion

- ci/script.sh
- example/src/main.rs
- libfuzzer/FuzzerInterceptors.cpp
- libfuzzer/dataflow/DataFlow.cpp
> Update libFuzzer to llvm/llvm-project@60e32a1

- src/lib.rs
This change is an attempt to address the behavior found at
google/oss-fuzz#8389 where two distinct bugs were accidentally
deduplicated into the same bug report. One of the reasons for this is
that the stack traces between the two bugs were almost the same with
only very minor differences. My hope is that by forcing a unique stack
frame per fuzzer this will be less likely since there is guaranteed to
be at least one stack frame per fuzz target which is unique with this
change.
While I was here I wrapped up the generated function by the
`fuzz_target!` macro in a `const _: () = { ... }` to avoid adding this
new `run` function in to the normal module's namespace and accidentally
causing name collisions (e.g. if fuzz targets already have functions
named `run`)
> Force at least one unique stack frame per fuzzer

- src/lib.rs
This allows the fuzz target to indiciate whether an input was useful for the fuzz testing by returning Corpus::Keep or Corpus::Reject. Backwards compatibility is preserved by coercing the unit type () to Corpus::Keep.
This maps to 0 (Keep) and -1 (Reject) in the libFuzzer API: https://llvm.org/docs/LibFuzzer.html#rejecting-unwanted-inputs
> Enable keep/reject inputs from the corpus

- build.rs
Makes libfuzzer_sys rebuild if the custom libfuzzer path changes and use the correct lib name if the library is double-prefixed ("liblib").
> Fix minor build.rs issues w.r.t. custom libfuzzer paths

- src/lib.rs
The `fuzz_target!` macro's input is designed to follow Rust's closure syntax, and mimics nearly all the syntax features of Rust closures: optional argument type, optional return type. 
However, it diverged from Rust closures in requiring the body of the "closure" to always be surrounded in curly braces, due to the use of $:block.
I had a fuzz target where I had to end up doing the following:
```rust
fuzz_target!(|bytes: &[u8]| { do_fuzz(bytes, true) });
```
The braces here diverge from how the equivalent closure would ordinarily be written. Punctuation which is required but doesn't serve a purpose detracts from the readability of the program.
This PR makes the braces around a "closure" body optional.
```rust
fuzz_target!(|bytes: &[u8]| do_fuzz(bytes, true));
```
> Allow "closure" body to be any expression, not only block

- Cargo.toml
- README.md
- build.rs
We are implementing https://github.com/AFLplusplus/LibAFL/pull/981, but don't want to make too much impact on the downstream users of libfuzzer-sys. As a compromise, this PR adds a default feature, `link`, which, when enabled, links to the libfuzzer runtime or the CUSTOM_LIBFUZZER_RUNTIME. When not enabled, it does not link to the fuzzer runtime.
This allows us to link to a custom runtime in our own dependency while reusing the infrastructure already provided by libfuzzer-sys (namely, fuzz_target and custom_mutator). See an example of this use case here:
https://github.com/AFLplusplus/LibAFL/blob/libfuzzer/libafl_libfuzzer/build.rs
https://github.com/AFLplusplus/LibAFL/blob/libfuzzer/libafl_libfuzzer/Cargo.toml#L17
> Make it possible to link to custom runtime in another dep

- src/lib.rs
These functions define specific symbols that libfuzzer looks for, and are only intended to be called by libfuzzer and with the contract that it guarantees. So make sure they are `unsafe` and hidden from docs and all that.
> Mark internal, fuzzer hook functions as `unsafe`

- CHANGELOG.md
- libfuzzer/CMakeLists.txt
- libfuzzer/FuzzerCommand.h
- libfuzzer/FuzzerCorpus.h
- libfuzzer/FuzzerDataFlowTrace.cpp
- libfuzzer/FuzzerDriver.cpp
- libfuzzer/FuzzerFlags.def
- libfuzzer/FuzzerFork.cpp
- libfuzzer/FuzzerIO.cpp
- libfuzzer/FuzzerIO.h
- libfuzzer/FuzzerInternal.h
- libfuzzer/FuzzerLoop.cpp
- libfuzzer/FuzzerMerge.cpp
- libfuzzer/FuzzerMutate.cpp
- libfuzzer/FuzzerTracePC.cpp
- libfuzzer/FuzzerUtil.h
- libfuzzer/FuzzerUtilDarwin.cpp
- libfuzzer/FuzzerUtilFuchsia.cpp
- libfuzzer/FuzzerUtilLinux.cpp
- libfuzzer/FuzzerUtilPosix.cpp
- libfuzzer/FuzzerUtilWindows.cpp
- libfuzzer/build.sh
- libfuzzer/scripts/unbalanced_allocs.py
- libfuzzer/tests/CMakeLists.txt
Update the LLVM compiler-rt C++ code to the top of the 18.x branch
The summary of the changes from compiler-rt 15 (the last time this code was updated) are:
1. Improvements to Ctrl+C detection and closing out of a fuzzing session
2. Loop optimizations, in preventing copy operations
3. Dynamic pagesize detection
4. Setting Worker thread names (on Linux)
5. Use of a bitset data structure to track rarity of features "improves fuzzer throughput rather dramatically (close to 2x) in early exploratory phases"
The LLVM commits which make up the changes in this commit come from the squash of the following LLVM commits:
```sh
git log --format=reference origin/release/15.x..release/18.x -- compiler-rt/lib/fuzzer/
```
```
3747cde5e84f ([Fuzzer] Enable custom libc++ for Android (#70407), 2023-11-02) …
```
> Update libfuzzer code to compiler-rt 18

- Cargo.toml
- src/lib.rs
In favor of `LazyLock`.
Needs Rustc 1.80 that will be released in ten days.
> Remove `once_cell`

- .github/workflows/rust.yml
- README.md
- libfuzzer/FuzzerDriver.cpp
- libfuzzer/FuzzerFork.cpp
- libfuzzer/FuzzerUtilFuchsia.cpp
- libfuzzer/FuzzerUtilLinux.cpp
- libfuzzer/FuzzerUtilWindows.cpp
- libfuzzer/build.sh
- libfuzzer/tests/CMakeLists.txt
- update-libfuzzer.sh
This PR does a few related things:
* Makes the update script much faster to run
* Adds a CI check that the `libfuzzer/` directory correctly reflects the commit that we claim we've vendored
* Updates our libfuzzer vendor to LLVM 19.x
@Manishearth care to take a look at this? Thanks!
> Update how we do libfuzzer vendoring

- Cargo.toml
Using https://github.com/actions/dependency-review-action in https://github.com/Chia-Network/chia_rs/actions/runs/11807687782/job/32894842447?pr=785 I got an error stating that the existing license short text `MIT/Apache-2.0/NCSA` is invalid from an SPDX perspective.
```
Licenses
Warning: 
The validity of the licenses of the dependencies below could not be determined. Ensure that they are valid SPDX licenses:
Cargo.lock » libfuzzer-sys@0.4.8 – License: MIT/Apache-2.0/NCSA
Error: Dependency review could not detect the validity of all licenses.
```
There was discussion with respect to Rust at https://github.com/rust-lang/cargo/issues/2174#issuecomment-355454163 and there are SPDX examples at https://spdx.dev/learn/handling-license-info/.
> update package license string to be spdx compatible
